
[font]
size = 9.0

[font.normal]
family = "JetBrains Mono Medium"

[terminal.shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

[window]
opacity = 1

[window.dimensions]
columns = 140
lines = 38

[general]
import = ["/home/ez4kacchan/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[terminal]
